In [14]:
import pandas as pd
import numpy as np

In [15]:
df = pd.read_csv(r"C:\Users\jayani\Desktop\AI_Coursework\Dataset\smartcare_ai_dataset_1000.csv")

In [16]:
df.head()

,record_id,patient_id,age,gender,blood_group,department,diagnosis,appointment_date,waiting_days,previous_appointments,...,consultation_fee_lkr,room_charge_lkr,lab_charge_lkr,medicine_charge_lkr,total_bill_lkr,payment_status,payment_method,no_show,readmitted_30_days,disease_risk_level
0,1,P10001,53,Male,A-,General Medicine,Migraine,2025-04-10,10,1,...,2000,0,0,11596,13596,Paid,Insurance,0,0,High
1,2,P10002,26,Male,B-,General Medicine,Diabetes,2025-05-15,2,3,...,2000,0,0,3652,5652,Paid,Insurance,0,0,Medium
2,3,P10003,22,Male,B+,Orthopedics,Back Pain,2025-07-09,22,7,...,2500,0,1200,2562,6262,Unpaid,Insurance,1,0,Medium
3,4,P10004,44,Female,AB-,Cardiology,Asthma,2025-10-16,16,1,...,2000,0,5000,10262,17262,Paid,Online,0,0,Medium
4,5,P10005,51,Female,O+,Neurology,Hypertension,2025-12-18,12,4,...,4000,0,6000,10414,20414,Paid,Cash,0,0,Medium

In [17]:
df.shape

(1000, 33)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 33 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   record_id                     1000 non-null   int64
 1   patient_id                    1000 non-null   object
 2   age                           1000 non-null   int64
 3   gender                        1000 non-null   object
 4   blood_group                   1000 non-null   object
 5   department                    1000 non-null   object
 6   diagnosis                     1000 non-null   object
 7   appointment_date              1000 non-null   object
 8   waiting_days                  1000 non-null   int64
 9   previous_appointments         1000 non-null   int64
 10  missed_previous_appointments  1000 non-null   int64
 11  appointment_status            1000 non-null   object
 12  admitted                      1000 non-null   int64
 13  room_type                     94 non-null     object
 14  length_of_stay_days           1000 non-null   int64
 15  previous_admissions           1000 non-null   int64
 16  systolic_bp                   1000 non-null   int64
 17  diastolic_bp                  1000 non-null   int64
 18  blood_sugar_mg_dl             1000 non-null   int64
 19  cholesterol_mg_dl             1000 non-null   int64
 20  bmi                           1000 non-null   float64
 21  lab_tests_count               1000 non-null   int64
 22  treatments_count              1000 non-null   int64
 23  consultation_fee_lkr          1000 non-null   int64
 24  room_charge_lkr               1000 non-null   int64
 25  lab_charge_lkr                1000 non-null   int64
 26  medicine_charge_lkr           1000 non-null   int64
 27  total_bill_lkr                1000 non-null   int64
 28  payment_status                1000 non-null   object
 29  payment_method                1000 non-null   object
 30  no_show                       1000 non-null   int64
 31  readmitted_30_days            1000 non-null   int64
 32  disease_risk_level            1000 non-null   object
dtypes: float64(1), int64(21), object(11)
memory usage: 257.9+ KB

In [19]:
df.describe()

,record_id,age,waiting_days,previous_appointments,missed_previous_appointments,admitted,length_of_stay_days,previous_admissions,systolic_bp,diastolic_bp,...,bmi,lab_tests_count,treatments_count,consultation_fee_lkr,room_charge_lkr,lab_charge_lkr,medicine_charge_lkr,total_bill_lkr,no_show,readmitted_30_days
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,...,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,44.744000,21.851000,2.884000,0.553000,0.330000,1.103000,0.85500,128.423000,78.828000,...,25.519100,2.292000,1.805000,2820.500000,2412.50000,4869.600000,7971.000000,18073.600000,0.495000,0.253000
std,288.819436,17.851474,13.040892,1.693343,0.740094,0.470448,1.885191,0.95859,15.486895,10.043669,...,4.252852,1.679749,1.596723,837.694146,11140.88026,4122.515127,4629.777041,13710.258789,0.500225,0.434948
min,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,85.000000,50.000000,...,14.000000,0.000000,0.000000,1500.000000,0.00000,0.000000,506.000000,2954.000000,0.000000,0.000000
25%,250.750000,33.000000,11.000000,2.000000,0.000000,0.000000,0.000000,0.00000,117.000000,72.000000,...,22.700000,1.000000,1.000000,2000.000000,0.00000,2400.000000,4316.500000,11018.000000,0.000000,0.000000
50%,500.500000,44.000000,22.000000,3.000000,0.000000,0.000000,0.000000,1.00000,128.000000,79.000000,...,25.600000,2.000000,1.000000,3000.000000,0.00000,3600.000000,7680.000000,15068.500000,0.000000,0.000000
75%,750.250000,57.000000,34.000000,4.000000,1.000000,1.000000,2.000000,1.00000,139.000000,86.000000,...,28.300000,3.000000,3.000000,3500.000000,0.00000,6300.000000,11032.000000,20870.000000,1.000000,1.000000
max,1000.000000,90.000000,44.000000,10.000000,4.000000,1.000000,9.000000,5.00000,178.000000,111.000000,...,38.800000,10.000000,10.000000,4000.000000,150000.00000,27000.000000,20371.000000,179528.000000,1.000000,1.000000

In [20]:
df.columns

Index(['record_id', 'patient_id', 'age', 'gender', 'blood_group', 'department',
       'diagnosis', 'appointment_date', 'waiting_days',
       'previous_appointments', 'missed_previous_appointments',
       'appointment_status', 'admitted', 'room_type', 'length_of_stay_days',
       'previous_admissions', 'systolic_bp', 'diastolic_bp',
       'blood_sugar_mg_dl', 'cholesterol_mg_dl', 'bmi', 'lab_tests_count',
       'treatments_count', 'consultation_fee_lkr', 'room_charge_lkr',
       'lab_charge_lkr', 'medicine_charge_lkr', 'total_bill_lkr',
       'payment_status', 'payment_method', 'no_show', 'readmitted_30_days',
       'disease_risk_level'],
      dtype='object')

In [21]:
print(df["no_show"].head())

0    0
1    0
2    1
3    0
4    0
Name: no_show, dtype: int64

In [22]:
df.isnull().sum()

record_id                         0
patient_id                        0
age                               0
gender                            0
blood_group                       0
department                        0
diagnosis                         0
appointment_date                  0
waiting_days                      0
previous_appointments             0
missed_previous_appointments      0
appointment_status                0
admitted                          0
room_type                       906
length_of_stay_days               0
previous_admissions               0
systolic_bp                       0
diastolic_bp                      0
blood_sugar_mg_dl                 0
cholesterol_mg_dl                 0
bmi                               0
lab_tests_count                   0
treatments_count                  0
consultation_fee_lkr              0
room_charge_lkr                   0
lab_charge_lkr                    0
medicine_charge_lkr               0
total_bill_lkr                    0
payment_status                    0
payment_method                    0
no_show                           0
readmitted_30_days                0
disease_risk_level                0
dtype: int64

In [23]:
df.duplicated().sum()

np.int64(0)

In [24]:
df.dtypes

record_id                         int64
patient_id                       object
age                               int64
gender                           object
blood_group                      object
department                       object
diagnosis                        object
appointment_date                 object
waiting_days                      int64
previous_appointments             int64
missed_previous_appointments      int64
appointment_status               object
admitted                          int64
room_type                        object
length_of_stay_days               int64
previous_admissions               int64
systolic_bp                       int64
diastolic_bp                      int64
blood_sugar_mg_dl                 int64
cholesterol_mg_dl                 int64
bmi                             float64
lab_tests_count                   int64
treatments_count                  int64
consultation_fee_lkr              int64
room_charge_lkr                   int64
lab_charge_lkr                    int64
medicine_charge_lkr               int64
total_bill_lkr                    int64
payment_status                   object
payment_method                   object
no_show                           int64
readmitted_30_days                int64
disease_risk_level               object
dtype: object

In [25]:
df.nunique()

record_id                       1000
patient_id                      1000
age                               88
gender                             2
blood_group                        8
department                         7
diagnosis                         10
appointment_date                 339
waiting_days                      45
previous_appointments             10
missed_previous_appointments       5
appointment_status                 4
admitted                           2
room_type                          3
length_of_stay_days               10
previous_admissions                6
systolic_bp                       83
diastolic_bp                      58
blood_sugar_mg_dl                120
cholesterol_mg_dl                172
bmi                              197
lab_tests_count                   11
treatments_count                  11
consultation_fee_lkr               6
room_charge_lkr                   22
lab_charge_lkr                    29
medicine_charge_lkr              966
total_bill_lkr                   981
payment_status                     3
payment_method                     4
no_show                            2
readmitted_30_days                 2
disease_risk_level                 3
dtype: int64